## Pandas Study

### reference or copy of a Slice Action

In [1]:
import numpy as np
import pandas as pd

When creat DF from nparray, the dtype of elements in DF is fixed:

In [29]:
df = pd.DataFrame(np.ones((3,3)))
# df.iloc[0,2] = [1,2]  # error: setting an array element with a sequence
type(df.iloc[0,2]) # numpy.float64
type(df.iloc[0])  # pandas.core.series.Series
type(df.iloc[0:2,0]) # pandas.core.series.Series
# df.iloc[0] = [1,1,[2,3]] # error: setting an array element with a sequence

pandas.core.series.Series

==================================================================================  
#### Ref:

In [54]:
df = pd.DataFrame([[1,1,[2,3]],[1,1,1],[1,1,1]],columns = ['A','B','C'])
df

A  B       C
0  1  1  [2, 3]
1  1  1       1
2  1  1       1

In [55]:
df2 = df
df2.iloc[0,0] = 999
df2.iloc[0,1] = 998
df2.iloc[0,2][0] = 997
df2.columns = ['a','b','c']
df

a    b         c
0  999  998  [997, 3]
1    1    1         1
2    1    1         1

In [56]:
df2.columns == df.columns

array([ True,  True,  True])

In [57]:
df2.columns is df.columns

True

==================================================================================  
#### deep copy:

In [61]:
df = pd.DataFrame([[1,1,[2,3]],[1,1,1],[1,1,1]],columns = ['A','B','C'])
df

A  B       C
0  1  1  [2, 3]
1  1  1       1
2  1  1       1

In [62]:
df2 = df.copy(True)
df2.iloc[0,0] = 999
df2.iloc[0,1] = 998
df2.iloc[0,2][0] = 997
df2.columns = ['a','b','c']
df

A  B         C
0  1  1  [997, 3]
1  1  1         1
2  1  1         1

In [63]:
df2.columns

Index(['a', 'b', 'c'], dtype='object')

In [43]:
df2.columns == df.columns

array([False, False, False])

==================================================================================  
#### normal copy:

In [64]:
df = pd.DataFrame([[1,1,[2,3]],[1,1,1],[1,1,1]],columns = ['A','B','C'])
df

A  B       C
0  1  1  [2, 3]
1  1  1       1
2  1  1       1

In [65]:
df2 = df.copy()
df2.iloc[0,0] = 999
df2.iloc[0,1] = 998
df2.iloc[0,2][0] = 997
df2.columns = ['a','b','c']
df

A  B         C
0  1  1  [997, 3]
1  1  1         1
2  1  1         1

In [66]:
df2.columns == df.columns

array([False, False, False])

==================================================================================  
#### normal copy:

In [67]:
df = pd.DataFrame([[1,1,[2,3]],[1,1,1],[1,1,1]],columns = ['A','B','C'])
df

A  B       C
0  1  1  [2, 3]
1  1  1       1
2  1  1       1

In [69]:
df2 = df[['A','B','C']]
df2.iloc[0,0] = 999
df2.iloc[0,1] = 998
df2.iloc[0,2][0] = 997
df2.columns = ['a','b','c']
df

A  B         C
0  1  1  [997, 3]
1  1  1         1
2  1  1         1

In [70]:
df2.columns == df.columns

array([False, False, False])

==================================================================================  
#### Reference:

In [93]:
df = pd.DataFrame([[1,1,[2,3]],[1,1,1],[1,1,1]],columns = ['A','B','C'])
df

A  B       C
0  1  1  [2, 3]
1  1  1       1
2  1  1       1

In [95]:
df2 = df['A'] # reference and alert
type(df2) # series
df2[0] = 998

df3 = df[['A','B']].copy()  # copy, add '.copy()' to avoid alert
df3.B[0] = 333
df3.loc[0,'B'] = 332
df

d:\Users\zhangyun29\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


A  B       C
0  998  1  [2, 3]
1    1  1       1
2    1  1       1

==================================================================================  
#### copy:

In [115]:
df = pd.DataFrame([[6,6,[6,3],1,1],[1,1,1,1,1],[1,1,1,1,1],[6,1,1,1,1]],columns = ['A','B','C','D','E'])
df

A  B       C  D  E
0  6  6  [6, 3]  1  1
1  1  1       1  1  1
2  1  1       1  1  1
3  6  1       1  1  1

In [113]:
df2 = df.loc[0].copy() # copy, add '.copy()' to avoid alert
df2[0] = 998

df3 = df.loc[:,['A','B']]  # copy without alert
df3.B[0] = 333
df3.loc[0,'B'] = 332

df4 = pd.DataFrame() # copy without alert
df4['C'] = df['C']
df4.C[1] = 444

df5 = df.loc[3,:].copy()# copy, add '.copy()' to avoid alert
print(type(df5))
df5[0] = 555


df

<class 'pandas.core.series.Series'>


A  B       C  D  E
0  5  5  [5, 3]  1  1
1  1  1       1  1  1
2  1  1       1  1  1
3  5  1       1  1  1

### various warning 

In [117]:
df = pd.DataFrame([[6,6,[6,3],1,1],[1,1,1,1,1],[1,1,1,1,1],[6,1,1,1,1]],columns = ['A','B','C','D','E'])

In [118]:
df2 = df[['A','B','C','D','E']]

In [119]:
df3 = df[['A','B']]

In [120]:
df2.iloc[0,0] = 999

In [121]:
df2.B[0] = 333

d:\Users\zhangyun29\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [122]:
df3.iloc[0,0] = 999

d:\Users\zhangyun29\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\core\indexing.py:194: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
d:\Users\zhangyun29\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [126]:
df3.B[0] = 333

d:\Users\zhangyun29\AppData\Local\Programs\Python\Python36-32\lib\site-packages\IPython\core\interactiveshell.py:2910: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  exec(code_obj, self.user_global_ns, self.user_ns)


In [123]:
df == df[['A','B','C','D','E']]

A     B     C     D     E
0  True  True  True  True  True
1  True  True  True  True  True
2  True  True  True  True  True
3  True  True  True  True  True

In [124]:
df is df[['A','B','C','D','E']]

False

### remove warning from above sample 

In [2]:
df = pd.DataFrame([[1,1,[2,3],1,1],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1]],columns = ['A','B','C','D','E'])

In [180]:
df2 = df.loc[0:2,['A','B']]
df2.A[0] = 999 # copy, without alert
df2.A = [2,2,2] # copy, without alert
df2.loc[1,:] = [3,3] # copy, without alert
df2.loc[1] = [33,33] # copy, without alert
df2.iloc[:,0] = [4,4,4] # copy, without alert
df2.loc[0,'B'] = 998 # copy, without alert
df2

A    B
0  4  998
1  4   33
2  4    1

In [195]:
df3 = df.iloc[0:2,0:3].copy()
df3.A[0] = 993 # copy/alert, add".copy()" still alert, add df3.is_copy = 'T/F' still alert
df3.A = [2,2] # copy, without alert
df3.loc[1,:] = [3,3,3] # copy, without alert
df3.loc[1] = [33,33,33] # copy, without alert

d:\Users\zhangyun29\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [174]:
df22 = df.loc[0,:]
df22[0] = 922 # copy, add".copy()" without alert

In [135]:
df221 = df.loc[0]

In [132]:
df222 = df.loc[0,['A','B']]

In [133]:
df23 = df.loc[:,'A']

In [134]:
df232 = df.loc[0:2,'A']

In [6]:
df32 = df.iloc[0,:]
df32.A = 32 # copy, add".copy()" remove alert
df_r = pd.DataFrame()
df_r = df.copy()
df_r.iloc[0] = df32
df32

d:\Users\zhangyun29\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\core\generic.py:3643: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value


A        32
B         1
C    [2, 3]
D         1
E         1
Name: 0, dtype: object

In [186]:
df321 = df.iloc[0]
df321.A = 321 # copy/alert, add".copy()" OK, add df3.is_copy = 'T/F' still alert

In [138]:
df322 = df.iloc[0,0:3]

In [139]:
df33 = df.iloc[:,0]

In [140]:
df332 = df.iloc[0:2,0]

In [5]:
df

A  B       C  D  E
0  1  1  [2, 3]  1  1
1  1  1       1  1  1
2  1  1       1  1  1
3  1  1       1  1  1

## id of slice of a dataframe
all types of slices of dataframe are immutable object

In [ ]:
df = pd.DataFrame([[1,1,[2,3],1,1],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1]],columns = ['A','B','C','D','E'])

In [22]:
df.loc[0,'A'] = 999

In [23]:
df

A  B       C  D  E
0  999  1  [2, 3]  1  1
1    1  1       1  1  1
2    1  1       1  1  1
3    1  1       1  1  1

### df reference:

In [24]:
id(df),id(df[['A','B','C','D','E']]),id(df.loc[:,:]),id(df.iloc[:,:]),id(df.columns),id(df.index)
# origin: (179155696, 179157232, 179155696, 179155696, 179155792, 179155536)
# change: (179155696, 179157936, 179155696, 179155696, 179155792, 179155536)

(179155696, 179157936, 179155696, 179155696, 179155792, 179155536)

### columns' reference:

In [25]:
id(df.A),id(df['A']),id(df.loc[:,'A']),id(df.iloc[:,0])
# origin:(178903696, 178903696, 178903696, 179156912)
# change:(179157392, 179157392, 179157392, 179157744)

(179157392, 179157392, 179157392, 179157744)

In [20]:
type(df.A),type(df['A']),type(df.loc[:,'A']),type(df.iloc[:,0])

(pandas.core.series.Series,
 pandas.core.series.Series,
 pandas.core.series.Series,
 pandas.core.series.Series)

### rows' reference:

In [26]:
id(df.loc[0]),id(df.loc[0,:]),id(df.iloc[0]),id(df.iloc[0,:])
# origin:(179157040, 179156720, 179157040, 179157136)
# change:(179158160, 179155664, 179158160, 179157936)

(179158160, 179155664, 179158160, 179157936)

In [19]:
type(df.loc[0]),type(df.loc[0,:]),type(df.iloc[0]),type(df.iloc[0,:])

(pandas.core.series.Series,
 pandas.core.series.Series,
 pandas.core.series.Series,
 pandas.core.series.Series)

### slice reference:

In [ ]:
id(df)